# Generated by Django 5.0.1 on 2024-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmember',
            name='achievements',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_interests',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
