# Generated by Django 5.0.1 on 2024-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_councilmember_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('COMPUTER', 'Comps'), ('IT', 'IT'), ('AIML', 'AIML'), ('DE', 'DE'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.TextField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], null=True),
        ),
    ]
