# Generated by Django 5.0.1 on 2025-01-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('AS&H', 'AS&H'), ('COMPUTER', 'Comps'), ('IT', 'IT'), ('AIML', 'AIML'), ('DE', 'DE'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
