# Generated by Django 5.0.1 on 2025-01-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='subjects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
