# Generated by Django 5.0.1 on 2024-11-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('INTRA', 'Intra College'), ('INTER', 'Inter College')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(upload_to='events/')),
                ('banner_image', models.ImageField(upload_to='events/banners/')),
                ('rules_document', models.FileField(null=True, upload_to='events/rules/')),
                ('schedule_file', models.FileField(null=True, upload_to='events/schedules/')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('TECHNICAL', 'Technical'), ('ACADEMIC', 'Academic')], max_length=20)),
                ('schedule', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField()),
                ('registration_deadline', models.DateTimeField()),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rules', models.TextField()),
                ('scoring_criteria', models.TextField()),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
