# Generated by Django 5.0.1 on 2024-11-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.councilmember'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judged_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subevent',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinated_subevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.subevent'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.subevent'),
        ),
    ]
