# Generated by Django 5.0.1 on 2025-01-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventscore_position_eventscore_qualified_for_next_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
    ]
