# Generated by Django 5.0.1 on 2024-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='department',
            field=models.CharField(choices=[('COMPUTER', 'Comps'), ('IT', 'IT'), ('AIML', 'AIML'), ('DE', 'DE'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
