# Generated by Django 5.0.1 on 2025-01-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_subeventimage_sub_event_alter_subeventimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='sub_events', to='events.subeventimage'),
        ),
    ]
