# Generated by Django 5.0.1 on 2025-01-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_subevent_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
