# Generated by Django 5.0.1 on 2025-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_subevent_format_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='registration_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='registration_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
