# Generated by Django 5.0.1 on 2025-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_subevent_registration_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='reporting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
