# Generated by Django 5.0.1 on 2025-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_subevent_date_subevent_reporting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='gender_participation',
            field=models.CharField(blank=True, choices=[('ALL', 'All'), ('MALE', 'Boys Only'), ('FEMALE', 'Girls Only')], default='ALL', help_text='Specify if the event is open to all or restricted by gender', max_length=10, null=True),
        ),
    ]
