# Generated by Django 5.0.1 on 2025-01-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventscore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscore',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
