# Generated by Django 5.0.1 on 2025-01-05 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventscore_time_taken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEventFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(limit_choices_to={'user_type': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='judging_events', to=settings.AUTH_USER_MODEL)),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='events.subevent')),
            ],
            options={
                'verbose_name': 'Sub Event Faculty',
                'verbose_name_plural': 'Sub Event Faculties',
                'unique_together': {('sub_event', 'faculty')},
            },
        ),
        migrations.AddField(
            model_name='subevent',
            name='faculty_judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='judged_sub_events', through='events.SubEventFaculty', to=settings.AUTH_USER_MODEL),
        ),
    ]
