# Generated by Django 5.0.1 on 2025-01-05 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_subeventfaculty_subevent_faculty_judges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='faculty_judges',
            field=models.ManyToManyField(blank=True, related_name='judged_sub_events', through='events.SubEventFaculty', to=settings.AUTH_USER_MODEL),
        ),
    ]
