# Generated by Django 5.0.1 on 2025-01-05 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_subeventfaculty_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subeventfaculty',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'user_type': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='judging_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
