# Generated by Django 5.0.1 on 2025-01-05 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_subeventfaculty_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.subevent')),
            ],
            options={
                'unique_together': {('department', 'year', 'division', 'sub_event')},
            },
        ),
    ]
