# Generated by Django 5.0.1 on 2025-01-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_departmentscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
            ],
            options={
                'verbose_name': 'Scoreboard',
                'verbose_name_plural': 'Scoreboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.departmentscore',),
        ),
    ]
