# Generated by Django 5.0.1 on 2025-01-05 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_rename_scheduled_time_eventheat_schedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subeventfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subeventfaculty',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.subevent'),
        ),
    ]
