# Generated by Django 5.0.1 on 2025-01-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_subeventfaculty_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subeventfaculty',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='events.subevent'),
        ),
    ]
