# Generated by Django 5.0.1 on 2025-01-05 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_subeventfaculty_sub_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subeventfaculty',
            options={},
        ),
        migrations.AlterField(
            model_name='subeventfaculty',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'user_type': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
