# Generated by Django 5.0.1 on 2025-01-06 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_subeventfaculty_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='chairpersons',
            field=models.ManyToManyField(blank=True, related_name='chaired_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_heads',
            field=models.ManyToManyField(blank=True, related_name='headed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='vice_chairpersons',
            field=models.ManyToManyField(blank=True, related_name='vice_chaired_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
