# Generated by Django 5.0.1 on 2025-01-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_event_chairpersons_alter_event_event_heads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventheat',
            name='heat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventheat',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
