# Generated by Django 5.0.1 on 2025-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_eventheat_heat_name_alter_eventheat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscore',
            name='score_type',
            field=models.CharField(blank=True, choices=[('WINNER', 'Winner'), ('RUNNER_UP', 'Runner Up'), ('PARTICIPANT', 'Participant')], max_length=20, null=True),
        ),
    ]
