# Generated by Django 5.0.1 on 2025-01-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_eventscore_score_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentscore',
            name='points',
        ),
        migrations.AddField(
            model_name='departmentscore',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
