# Generated by Django 5.0.1 on 2025-01-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_remove_departmentscore_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventheat',
            options={'ordering': ['stage', 'round_number', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='eventheat',
            unique_together=set(),
        ),
    ]
