# Generated by Django 5.0.1 on 2025-01-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_eventheat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='department',
            field=models.CharField(blank=True, choices=[('COMPUTER', 'Comps'), ('IT', 'IT'), ('AIML', 'AIML'), ('DE', 'DE'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
