# Generated by Django 5.0.1 on 2025-01-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_eventregistration_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='upload_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='department',
            field=models.CharField(blank=True, choices=[('AS&H', 'AS&H'), ('COMPUTER', 'Comps'), ('IT', 'IT'), ('AIML', 'AIML'), ('DE', 'DE'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
