# Generated by Django 5.0.1 on 2025-01-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_subevent_upload_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('CULTURAL', 'Cultural Event'), ('SPORTS', 'Sports Event'), ('SPECIAL', 'Special Event')], max_length=20)),
                ('criteria', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Event Criteria',
            },
        ),
        migrations.AddField(
            model_name='eventheat',
            name='heat_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterUniqueTogether(
            name='eventheat',
            unique_together={('sub_event', 'stage', 'round_number', 'heat_number')},
        ),
        migrations.AlterModelOptions(
            name='eventheat',
            options={'ordering': ['round_number', 'heat_number']},
        ),
        migrations.AlterModelOptions(
            name='eventscore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subeventfaculty',
            options={'verbose_name_plural': 'Sub Event Faculty'},
        ),
        migrations.AlterUniqueTogether(
            name='departmentscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='eventscore',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='heatparticipant',
            name='created_at',
        ),
        migrations.AddField(
            model_name='departmentscore',
            name='aura_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventheat',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='aura_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='match_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='heatparticipant',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heatparticipant',
            name='qualified_for_next',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heatparticipant',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='allow_joint_winners',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='allow_negative_marking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='aura_points_runner',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='aura_points_winner',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='match_points_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='scoring_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard Scoring'), ('SPORTS_GROUP', 'Sports Group Event'), ('SPORTS_SOLO', 'Sports Solo Event'), ('CULTURAL_GROUP', 'Cultural Group Event'), ('CULTURAL_SOLO', 'Cultural Solo Event'), ('SPECIAL', 'Special Event')], default='STANDARD', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='scoring_criteria',
            field=models.ForeignKey(
                'EventCriteria',
                null=True,
                blank=True,
                on_delete=models.SET_NULL
            ),
        ),
        migrations.AlterField(
            model_name='departmentscore',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='departmentscore',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='departmentscore',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventheat',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventheat',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventheat',
            name='stage',
            field=models.CharField(blank=True, choices=[('REGISTRATION', 'Registration'), ('PRELIMS', 'Preliminaries'), ('QUARTERS', 'Quarter Finals'), ('SEMIS', 'Semi Finals'), ('FINALS', 'Finals')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventheat',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventheat',
            name='sub_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.subevent'),
        ),
        migrations.AlterField(
            model_name='eventheat',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('DISQUALIFIED', 'Disqualified')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='score_type',
            field=models.CharField(blank=True, choices=[('WINNER', 'Winner'), ('RUNNER_UP', 'Runner Up'), ('JOINT_WINNER', 'Joint Winner'), ('PARTICIPANT', 'Participant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='scoring_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcriteria'),
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='eventheat',
            name='heat_name',
        ),
    ]
