# Generated by Django 5.0.1 on 2025-01-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_fix_subevent_scoring_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('total_aura_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('department', 'year', 'division')},
            },
        ),
    ]
