# Generated by Django 5.0.1 on 2025-01-17 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_departmenttotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='sub_heads',
            field=models.ManyToManyField(blank=True, help_text='Select council members who will manage this sub-event', limit_choices_to={'is_active': True, 'user_type': 'COUNCIL'}, related_name='managed_sub_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
