# Generated by Django 5.0.1 on 2025-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_subevent_sub_heads'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventheat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventheat',
            name='heat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
