services:
  - type: web
    name: student-council-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sc_backend.wsgi:application --bind=0.0.0.0:$PORT --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir=/dev/shm"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: student_council_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: sc_backend.settings
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "student-council-backend.onrender.com,localhost,127.0.0.1"
    healthCheckPath: /admin/
    autoDeploy: false

databases:
  - name: student_council_db
    databaseName: student_council
    user: student_council
    plan: free