# Generated by Django 5.0.1 on 2024-12-30 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('achievement_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('RESEARCH', 'Research'), ('INNOVATION', 'Innovation'), ('SOCIAL', 'Social Work')], max_length=20)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='achievements/')),
                ('certificate', models.FileField(null=True, upload_to='achievements/certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('achiever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
